name = "romenn"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

[assets]
directory = "dist"

[vars]
PUBLIC_API_URL = "https://api.romenninmobiliaria.es"
