name = "romenn"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_API_URL = "https://api.romenninmobiliaria.es"

[site]
bucket = "./dist/client"

[build]
command = "npm run build"
